Wave Defense Improvements
cortex-command-community/Cortex-Command-Community-Project-Data pull request #137
Opened 2022-11-02 10:54 UTC by Causeless

- Stop spawning engineers. It's wave defence, it's *really* annoying to have to track down some random guy digging at the end of every wave
- Don't open/close doors when we hit the edit phase. It's not necessary anymore due to pathing enhancements in the codebase
- Make door breaching tools far more likely to spawn, so the AI can better handle the stronger doors

2022-11-03 14:16 UTC, garethyr requested changes
One minor change recommendation

2022-11-03 15:01 UTC, Causeless commented on Base.rte/Activities/WaveDefense.lua
> +		if rand < 0.5 then
Sounds good to me. I'm likely to make some extra changes to this file pending some code work I'm doing, so hold off on this PR in any case.

2022-11-03 15:12 UTC, garethyr commented on Base.rte/Activities/WaveDefense.lua
> +		if rand < 0.5 then
Sure. Feel free to resolve this comment when you've dealt with it btw.

2022-11-04 13:53 UTC, garethyr approved these changes
I'm happy with the changes :)
Unfortunately there're merge conflicts from maxim's big lua cleanup. Once you sort those out I'll merge this in.

2022-11-05 00:45 UTC, MaximDude submitted a review, later dismissed

2022-11-05 14:07 UTC, garethyr requested changes
A few small changes

2022-11-05 14:07 UTC, garethyr commented on Base.rte/Activities/WaveDefense.lua
> +				-- Add objective points
Extra whitespace here

2022-11-05 14:07 UTC, garethyr commented on .gitignore
> +!Saves.rte/Index.ini
I guess this is more explicit about it, but you can also just follow the same gitignore structure as, say Metagames.rte. Ignore the folder but force add the index ini and it won't be ignored.
Change it if you want to, or don't, I just wanted to mention it.

2022-11-05 14:43 UTC, Causeless commented on Base.rte/AI/HumanBehaviors.lua
> +				meleeDist = Owner.IndividualRadius + (IsThrownDevice(Owner.EquippedItem) and 50 or 25);
Yep. There was a bug where actors would burn their blowtorch but be too far away.
Good suggestion on the throwing thing, I guess I can remove that in that case.

2022-11-05 14:43 UTC, Causeless commented on Base.rte/Activities/WaveDefense.lua
> +	self.AI.playerValue = self:LoadNumber("AI_playerValue");
Yeah, mainly just keeping old inconsistency. Makes sense to clean it up, I'll do that eventually

2022-12-17 16:46 UTC, garethyr submitted a review, later dismissed

2022-12-17 19:50 UTC, MaximDude submitted a review, later dismissed

2022-12-17 22:18 UTC, MaximDude approved these changes

2022-12-18 21:21 UTC, garethyr approved these changes

2022-12-18 21:21 UTC, merged