Actor+some misc penetration sounds
cortex-command-community/Cortex-Command-Community-Project-Data pull request #59
Opened 2020-09-12 14:59 UTC by pawnishoovy

Adds organized penetration sounds in Base.rte. NO definitions, only .wav files.

Techion and Imperatus robots are to use Generic robot sounds but with their respective sweeteners on top, SpaceAge or Industrial. Apply to other robots as needed (such as brainbot)

ExitSweeteners are to be played on ExitWounds.

There's a bunch of .txts that should be incorporated into Credits.txt.

2020-09-14 19:47 UTC, garethyr requested changes
As mentioned in discord, please merge the credits files so they're all nice and organized. Outside of that, great stuff!

2020-09-15 11:42 UTC, fourZK requested changes
I trust that the sounds themselves are great (I will test them once I start adding them in), but here's just a couple of points about organization:
- Should the Dummy directory be renamed to Plastic or something instead? Also, if the Silver Man sounds are specific to the Silver Man and distinguished from the generic spaceage sounds, shouldn't they be listed in Techion.rte?
- Don't get me wrong, I think ExitSweetner is a neat term, but is it the right kind of technical term? (I actually don't know, I'm also okay with it staying)

2020-09-15 15:34 UTC, fourZK submitted a review, later dismissed

2020-09-15 17:07 UTC, MaximDude requested changes
Change `Credits.txt` encoding back to ANSI and fix all the messed up characters.
And remember not to change it whenever you're editing the file in the future.

2020-09-16 02:35 UTC, MaximDude approved these changes

2020-09-16 02:38 UTC, garethyr approved these changes

2020-09-16 02:51 UTC, merged