Added concrete and metal blocks to bits.
cortex-command-community/Cortex-Command-Community-Project-Data pull request #65
Opened 2020-10-17 18:10 UTC by tomflenniken

The two basic square blocks were not being included in the bunker bits menu. I've added them to where they used to be in the ordering (muscle memory wants them there).

2020-10-30 22:36 UTC, MaximDude requested changes
Move the presets back to where they were in the ini so they're on top of the list and just add the group property.

2020-10-30 22:57 UTC, tomflenniken commented
Any particular reason to have them at the top?

2020-10-31 00:10 UTC, MaximDude commented
For quick access because they're more common than the rest of the junk in that group.

2020-10-31 00:39 UTC, MaximDude approved these changes

2020-10-31 00:40 UTC, merged