Data followup to AEmitter and Jetpack changes
cortex-command-community/Cortex-Command-Community-Project-Data pull request #97
Opened 2021-06-11 11:06 UTC by fourZK

- Implemented ThrottleRange values across all vanilla jetpacks
- Lowered `EmissionDamage` values across most wounds after changes in damage logic

The emission damage got me thinking, if damage was to be calculated per only the last listed emission (as it was before), the emission damage would be steadier than if each emission accounted for it, since singular emissions can have their own PPM and thus create fluctuations in damage inflicted. Which one is ultimately better? Thoughts?

2021-06-14 21:34 UTC, garethyr commented on Imperatus.rte/Actors/Shared/Robot.lua
> +			self.Health = self.MaxHealth * (1 - self.WoundCount/self:GetGibWoundLimit(true, false, false)) * #limbs/5;
This confuses me. By my understanding it's making limb loss cause health damage, but
1. Why not just use breakwounds?
2. Bit of an edge case but if something adds a new arm with lua, this means the health will suddenly skyrocket for no discernible reason, right?

2021-06-14 21:36 UTC, garethyr requested changes
See file comment in Robot.lua

2021-06-14 21:36 UTC, garethyr commented on Imperatus.rte/Actors/Shared/Robot.lua
> +			self.Health = self.MaxHealth * (1 - self.WoundCount/self:GetGibWoundLimit(true, false, false)) * #limbs/5;
This confuses me. By my understanding it's making limb loss cause health damage, but
1. Why not just use breakwounds?
2. Bit of an edge case but if something adds a new arm with lua, this means the health will suddenly skyrocket for no discernible reason, right?

2021-06-22 18:28 UTC, MaximDude approved these changes

2021-06-23 02:24 UTC, garethyr approved these changes

2021-06-23 02:24 UTC, merged